### ISSUE TITLE
Calling connect after previously calling close fails

### ISSUE THREAD

**Issue by SRabbelier** [Gikkman/Java-Twirk#26]
After creating a Twirk instance, calling `connect()`, `close()`, `connect()`, results in:

`java.net.SocketException: Socket is closed`

This seems to be because in the [4.0 rewrite](https://github.com/Gikkman/Java-Twirk/commit/a6f897d1f5a4a3a2d739e995fb03b4b9c1a4075f#diff-63fdbf77f40806ea0298523afb1bee6b), `createResources` no longer creates a new socket and `releaseResources` does still close the socket.

**Comment by Gikkman** [comment]
Hm, looks like you are right. 

I vaguely remember I moved the socket creation out to a dedicated socket factory, so that users could provide their own. I must have forgotten to request a new socket from the factory once I closed the old socket.

I assume the way to go about this is keeping a reference to the socket factory that's passed to the Twirk builder, and request a socket from that one when we create resources. 

Thanks for the report. I'll take a look at it.
